Added docker file and config for pushgateaway image
luxteam/cis_tools pull request #105
Opened 2023-04-24 18:08 UTC by Flame0n

2023-04-28 11:08 UTC, Speedwag00n requested changes
Также нужны скрипты, джоба и ридми для сетапа экспортеров

2023-04-28 11:08 UTC, Speedwag00n commented on pusher/usage_info.py
> +            total_free_space += free_space_gb
Неиспользуемая переменная

2023-04-28 11:08 UTC, Speedwag00n commented on pusher/usage_info.py
> +        #total_percent = total_used / (total_used + total_free) * 100
Я бы собирал информацию о занятости дискового пространства в процентах

2023-04-28 11:08 UTC, Speedwag00n commented on pusher/usage_info.py
> +    parser.add_argument('--gpu', choices=['NVIDIA', 'AMD'], help='GPU type (NVIDIA or AMD). For monitoring gpu required libs \"gpustat\" for Nvidia windows\linux or \"pyamdgpuinfo\" for AMD linux')
Давай сделаем два requirements файла. Один под Nvidia, второй под AMD

2023-04-28 11:08 UTC, Speedwag00n commented on pusher/usage_info.py
> +        with mouse.Listener(on_move=on_move) as listener:
Добавь комментари о том, что тут происходит. В будущем можем забыть и с ходу будет не понятно

2023-04-28 11:08 UTC, Speedwag00n commented on pusher/usage_info.py
> +        with keyboard.Listener(on_press=on_press) as listener:
Аналогично нужен комментарий

2023-04-28 11:08 UTC, Speedwag00n commented on pusher/usage_info.py
> +                print(error)
Лучше еще выводить traceback. Иногда самой ошибки недостаточно для отладки

2023-04-28 11:08 UTC, Speedwag00n commented on pusher/usage_info.py
> +                print(error)
Лучше еще выводить traceback. Иногда самой ошибки недостаточно для отладки

2023-04-28 11:08 UTC, Speedwag00n commented on pusher/usage_info.py
> +        job_name = "testing" # Rename after end testing
Надо бы переименовать)

2023-05-07 13:39 UTC, Speedwag00n commented on pusher/usage_info.py
> +            total_free_space += free_space_gb
Не исправлено

2023-05-07 13:52 UTC, Speedwag00n requested changes

2023-05-07 13:52 UTC, Speedwag00n commented on pusher/README
> +execute_pusher.sh "https://localhost:9001" "user" "password"
Стоит просто перечислить с небольшим описанием все параметры для bat и sh скриптов. Примеры - это хорошо, но без общего описания параметров их будет маловато

2023-05-07 13:52 UTC, Speedwag00n commented on pusher/usage_info.py
> +            try:
Лучше разбить для читаемости на две функции. Для Nvidia и для AMD

2023-05-08 10:02 UTC, Speedwag00n approved these changes
По коду approve

2023-05-09 14:13 UTC, askravchenko commented on pusher/usage_info.py
> +            self.user_active = True
поскольку данная метрика будет и на фермовых машинах, то давай назовем её как-то по другому
например, device_is_idle или device_is_used

2023-05-09 14:13 UTC, askravchenko commented on pusher/usage_info.py
> +        if memory.percent > 20:
Сколько по умолчанию тратит винда? Если фермовая машина бездействует, то сколько оперативы затрачено?

2023-05-09 14:13 UTC, askravchenko commented on pusher/usage_info.py
> +        self.disk_usage_gauge.labels(hostname=self.hostname).set(total_percent)
У нас критично, если закончится место на диске C, но у тебя сумма
Т.е. если мы поставим артистам 1тб на С и 2-4тб на другом, то мы не узнаем что диск С закончился

2023-05-09 14:13 UTC, askravchenko commented on pusher/usage_info.py
> +            traceback.print_exc()
зачем в этом случае трейс?

2023-05-09 14:13 UTC, askravchenko commented on pusher/usage_info.py
> +            except Exception:
логирование можно добавить

2023-05-09 14:13 UTC, askravchenko commented on pusher/usage_info.py
> +            traceback.print_exc()
зачем в этом случае трейс?

2023-05-09 14:13 UTC, askravchenko commented on pusher/usage_info.py
> +                gpu_memory_usage = gpu_stats[0].memory_used / 1024 / 1024
сделай функцию с нормальным названием и везде использую её без магических чисел
мне непонятно из этого кода что ты получаешь и во что преобразуешь

2023-05-09 14:13 UTC, askravchenko commented on pusher/usage_info.py
> +        response.raise_for_status()
можно добавить логирование в случае >200, чтобы потом понять что произошло

2023-05-09 17:17 UTC, Flame0n commented on pusher/usage_info.py
> +        if memory.percent > 20:
До 15%

2023-05-09 17:18 UTC, Flame0n commented on pusher/usage_info.py
> +        self.cpu_usage_gauge = Gauge('cpu_usage_test', 'CPU usage percentage', ['hostname'], registry=self.registry)
Чтобы когда мы вмёржим PR и начнём собирать данные со всех компов, я мог поменять название метрики и у нас не будет старых данных. Старые данные из прометеуса не удалить, он их сам когда-нибудь удалит.

2023-06-19 12:39 UTC, Speedwag00n approved these changes

2023-06-20 11:52 UTC, askravchenko requested changes

2023-06-20 11:52 UTC, askravchenko commented on pusher/usage_info.py
>              if self.logger:
В таких случаях лучше уменьшать вложенность 
```python
if not self.logger:
    traceback.print_exc()
self.logger.error("ImportError pyamdgpuinfo", exc_info=True)
```

2023-06-20 11:52 UTC, askravchenko commented on pusher/usage_info.py
>              if self.logger:
И почему ты вызываешь traceback.print_exc(), а не логирование в файл?

2023-06-20 11:54 UTC, Flame0n commented on pusher/usage_info.py
>              if self.logger:
Это только для мануального тестирования, чтобы в файл не лезть, а просто в консоли отсматривать. В принципе можно это вообще удалить

2023-06-20 11:58 UTC, askravchenko commented
.\pusher\usage_info.py:14:1: E302 expected 2 blank lines, found 1
.\pusher\usage_info.py:15:58: E251 unexpected spaces around keyword / parameter equals
.\pusher\usage_info.py:15:60: E251 unexpected spaces around keyword / parameter equals
.\pusher\usage_info.py:35:121: E501 line too long (121 > 120 characters)
.\pusher\usage_info.py:37:121: E501 line too long (125 > 120 characters)
.\pusher\usage_info.py:39:121: E501 line too long (137 > 120 characters)
.\pusher\usage_info.py:41:121: E501 line too long (141 > 120 characters)
.\pusher\usage_info.py:63:121: E501 line too long (148 > 120 characters)
.\pusher\usage_info.py:64:121: E501 line too long (134 > 120 characters)
.\pusher\usage_info.py:68:1: W293 blank line contains whitespace
.\pusher\usage_info.py:78:14: E275 missing whitespace after keyword
.\pusher\usage_info.py:85:1: W293 blank line contains whitespace
.\pusher\usage_info.py:89:1: W293 blank line contains whitespace
.\pusher\usage_info.py:116:1: W293 blank line contains whitespace
.\pusher\usage_info.py:146:1: W293 blank line contains whitespace
.\pusher\usage_info.py:168:54: W291 trailing whitespace
.\pusher\usage_info.py:171:21: E128 continuation line under-indented for visual indent
.\pusher\usage_info.py:180:1: W293 blank line contains whitespace
.\pusher\usage_info.py:182:5: E303 too many blank lines (2)
.\pusher\usage_info.py:191:1: W293 blank line contains whitespace
.\pusher\usage_info.py:195:1: E305 expected 2 blank lines after class or function definition, found 1
.\pusher\usage_info.py:197:121: E501 line too long (197 > 120 characters)
.\pusher\usage_info.py:197:156: W605 invalid escape sequence '\l'
.\pusher\usage_info.py:205:29: W292 no newline at end of file

2023-06-20 12:01 UTC, askravchenko commented on pusher/usage_info.py
> +            self.gpu_usage_check_nvidia()
что будет если не нвидиа и не амд? стоит написать я думаю, что есть опечатка/ошибка

2023-06-20 12:02 UTC, askravchenko commented on pusher/usage_info.py
> +        except Exception:
HTTPError лучше перехватывать

2023-06-20 12:02 UTC, askravchenko commented on pusher/usage_info.py
> +    parser.add_argument('--gpu', choices=['NVIDIA', 'AMD'], help='GPU type (NVIDIA or AMD). For monitoring gpu required libs \"gpustat\" for Nvidia windows\linux or \"pyamdgpuinfo\" for AMD linux')
У нас нет возможности детектить какая гпу в системе стоит? АМД или нвидиа?

2023-06-20 12:03 UTC, askravchenko commented on pusher/usage_info.py
> +    parser.add_argument('--log', type=str, help='File with logs')
тут скорее Log path

2023-06-20 12:04 UTC, askravchenko commented on pusher/usage_info.py
> +        if log_file:
я бы сделал логер обязательным и просто логировал в файл рядом со скриптом. 
И вынес это из класса

2023-06-20 14:09 UTC, Flame0n commented
> 

.\usage_info.py:13:80: E501 line too long (80 > 79 characters)
.\usage_info.py:35:80: E501 line too long (87 > 79 characters)
.\usage_info.py:62:80: E501 line too long (84 > 79 characters)
.\usage_info.py:75:80: E501 line too long (88 > 79 characters)
.\usage_info.py:103:80: E501 line too long (82 > 79 characters)
.\usage_info.py:116:80: E501 line too long (84 > 79 characters)
.\usage_info.py:117:80: E501 line too long (148 > 79 characters)
.\usage_info.py:118:80: E501 line too long (137 > 79 characters)
.\usage_info.py:140:80: E501 line too long (86 > 79 characters)
.\usage_info.py:154:80: E501 line too long (82 > 79 characters)
.\usage_info.py:158:80: E501 line too long (80 > 79 characters)
.\usage_info.py:164:80: E501 line too long (86 > 79 characters)
.\usage_info.py:178:80: E501 line too long (86 > 79 characters)
.\usage_info.py:179:80: E501 line too long (83 > 79 characters)
.\usage_info.py:182:80: E501 line too long (84 > 79 characters)
.\usage_info.py:231:80: E501 line too long (81 > 79 characters)
.\usage_info.py:240:80: E501 line too long (83 > 79 characters)
.\usage_info.py:243:80: E501 line too long (86 > 79 characters)
.\usage_info.py:246:80: E501 line too long (84 > 79 characters)
.\usage_info.py:249:80: E501 line too long (83 > 79 characters)
.\usage_info.py:252:80: E501 line too long (80 > 79 characters)
.\usage_info.py:262:80: E501 line too long (83 > 79 characters)
.\usage_info.py:270:80: E501 line too long (87 > 79 characters)
.\usage_info.py:278:80: E501 line too long (87 > 79 characters)

Но мне кажется на это время тратить - такое себе

2023-06-20 14:12 UTC, Flame0n commented on pusher/usage_info.py
> +    parser.add_argument('--gpu', choices=['NVIDIA', 'AMD'], help='GPU type (NVIDIA or AMD). For monitoring gpu required libs \"gpustat\" for Nvidia windows\linux or \"pyamdgpuinfo\" for AMD linux')
Добавил

2023-06-20 14:13 UTC, Flame0n commented on pusher/usage_info.py
> +            self.gpu_usage_check_nvidia()
Теперь автодетектится

2023-06-20 14:14 UTC, Flame0n commented on pusher/usage_info.py
>              if self.logger:
На винде мы не собираем данные о АМД гпу. Так что завершать работу точно не вариант

2023-06-21 15:05 UTC, Speedwag00n requested changes

2023-06-22 11:58 UTC, merged